### ISSUE TITLE
Config views directory

### ISSUE THREAD

**Issue by ghislainf** [netson/l4gettext#14]
Hello,

Thanks for this package.
Can you use the `Config::get('view.paths')` without redifined the view directory in your config package. It's more flexible.

My views directory is on root project. And your call bellow forces me to extends your package.

```php
$views_folder = app_path() . DIRECTORY_SEPARATOR . $this->option('views_folder') . DIRECTORY_SEPARATOR;
```

Cheers :beer:

**Comment by netson** [comment]
Assumed solved; closing
