### ISSUE TITLE
Function setlocale() on Windows

### ISSUE THREAD

**Issue by rhulshof** [netson/l4gettext#3]
We love your package! However, on our development team several members develop on Windows clients. Up until now this hasn't been a problem. However, setlocale() works differently on Windows clients than on Unix-based systems, causing the LocaleNotFoundException to be thrown (which is uncatchable from within the L4 app, unfortunately).

We have managed to use GetText and PoEdit on previous projects on Windows environments, but this package refuses to work properly on Windows.

https://github.com/netson/l4gettext/blob/master/src/Netson/L4gettext/L4gettext.php#L107-L109

Windows setlocale(E_ALL, ...) refuses to accept locales like "en_US.utf8" and "en_US". However, "English", "German", "Dutch", etc. seem to work perfectly fine.

Is Windows support under consideration?

**Comment by daniel-rodas** [comment]
When setting locale on Windows you must uses a dash in the locale string instead of a dash.
So.
setlocale( LC_ALL, "en-US" ); 

Notice  "en-US" instead of  "en_US"
