### ISSUE TITLE
locale issue with l4gettext out of the box

### ISSUE THREAD

**Issue by loranger** [netson/l4gettext#9]
Hello, 
I have an issue right after the l4gettext installation on my mac.
Here is what I did :
- I have a up-to-date composer (`Composer version 3677c1ea6905b71daf8c3c4af716d2fe2d6f85bd 2014-05-03 07:46:50`)
- I create a new project (`composer create-project laravel/laravel myproject`)
- I require l4gettext (`composer require "netson/l4gettext:1.3.*"`)
- then update composer

Until there, everything is perfect.
Then I add the Service Provider and try to check artisan :

```
% ./artisan                                                                      ⏎
{"error":{"type":"Netson\\L4gettext\\LocaleNotFoundException","message":"The given locale [en_US.utf8] could not be set; it seems it does not exist on this system","file":"\/Users\/loranger\/Sites\/projects\/myproject\/vendor\/netson\/l4gettext\/src\/Netson\/L4gettext\/L4gettext.php","line":109}}
```

I use zsh on a french osx :

```
% locale
LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL="fr_FR.UTF-8"
```

Even if I change the locale in config/app.php, I still have this error message.
Did I miss something ?

**Comment by piep14** [comment]
Hello,

I have a same problem : 

The given locale [en_US] could not be set; it seems it does not exist on this system

And, I try 

php artisan l4gettext:fetc

But, i have an error : 

[Netson\L4gettext\FetchCommandNotSupportedOnWindowsException]
  The fetch command requires the cli command 'locale' to be available; this is not available on a windows system

Thank you for help

**Comment by netson** [comment]
The error message suggests you are running the package on a Windows machine, is that correct? The specific command doesn't work on windows as it requires the "locale" command, which is not available on windows systems. If you wish to select or install locales on a windows system, you will have to prepare these in advance. For example, check out [this link](http://superuser.com/questions/166089/where-is-the-list-of-available-windows-locales)

**Comment by piep14** [comment]
I did a "locale -a", and I found in the list

En_US
En_US.utf8

And yet I still have the mistake

I dont understand the example

**Comment by netson** [comment]
Are you running on Windows? As described in the docs, the command does not work on windows; I haven't tested it on windows and do not intend to officially support windows. If you're running on Linux, I can take another look at it. Happy new year!
